### ISSUE TITLE
Add Identitypool

### ISSUE THREAD

**Issue by rappeldo** [bsdkurt/aws-node-custom-user-pool#3]
I got the custom user pool working for me, the only issue I'm encountering is that I want to add a Identitypool like so

```
CognitoUserPoolUserPool:
      Type: "Custom::UserPool"
      Version: "1.0"
      DependsOn: CloudFormationCustomUserPoolLambdaFunction
      Properties:
        ServiceToken:
          Fn::GetAtt: [ "CloudFormationCustomUserPoolLambdaFunction", "Arn" ]
        Region:
          Ref: AWS::Region
        AccountId:
          Ref: AWS::AccountId
        PoolProperties:
          PoolName: ${self:provider.stage}-UserPool
          MfaConfiguration: OFF
          VerificationMessageTemplate:
            DefaultEmailOption: "CONFIRM_WITH_CODE"
          AdminCreateUserConfig:
            UnusedAccountValidityDays: 7
            AllowAdminCreateUserOnly: false
          AutoVerifiedAttributes:
            - email
          Policies:
            PasswordPolicy:
              RequireLowercase: true
              RequireSymbols: true
              RequireNumbers: true
              MinimumLength: 8
              RequireUppercase: true
          UsernameAttributes:
            - email
          Schema:
            - Name: name
              AttributeDataType: String
              Mutable: true
              Required: true
            - Name: email
              AttributeDataType: String
              Mutable: false
              Required: true
```

    # Creates a User Pool Client to be used by the identity pool
    CognitoUserPoolClientUserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: ${self:provider.stage}-UserPoolClient
        UserPoolId:
          Ref: CognitoUserPoolUserPool

    # Creates a federeated Identity pool
    IdentityPool:
      Type: "AWS::Cognito::IdentityPool"
      Properties:
        IdentityPoolName: xIdentity
        AllowUnauthenticatedIdentities: true
        CognitoIdentityProviders:
          - ClientId:
              Ref: CognitoUserPoolClientUserPoolClient
          - ProviderName:
              Fn::GetAtt: [CognitoUserPoolUserPool, ProviderName]
        SupportedLoginProviders:
          'graph.facebook.com': "xxxxxxxxxx"
          'accounts.google.com': "xxxxxxxxxx" # 123456789012.apps.googleusercontent.com`

The only problem is that I get this error message:

>  An error occurred: IdentityPool - CustomResource attribute error: Vendor response doesn't contain ProviderName key in object

The problem is that the custom userpool doesn't give back a ProvderName, any idea on how to make this work?
